SET TIMEZONE = 'UTC';

CREATE TABLE IF NOT EXISTS users (
  user_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  username VARCHAR(32) UNIQUE NOT NULL,
  email VARCHAR(256) NOT NULL,
  password VARCHAR(72) NOT NULL
);

CREATE TABLE IF NOT EXISTS videos (
  video_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  file_name VARCHAR(100) NOT NULL,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(1000) NOT NULL,
  aws_url VARCHAR(1000) NOT NULL,
  user_id INTEGER REFERENCES users (user_id),
  processed BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS video_versions (
  video_id INTEGER REFERENCES videos (video_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolution VARCHAR(16) NOT NULL,
  aws_url VARCHAR(1000) NOT NULL
);
