const {
  NODE_ENV,
  PG_URI,
  JWT_PUBLIC_KEY,
  REGION,
  S3_BUCKET,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  KAFKA_BROKER,
  KAFKA_VIDEO_RESOLUTION_TOPIC,
  KAFKA_VIDEO_SEARCH_INDEX_TOPIC,
} = process.env;

const PORT = process.env.PORT || 80;

export {
  NODE_ENV,
  PG_URI,
  JWT_PUBLIC_KEY,
  REGION,
  S3_BUCKET,
  PORT,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  KAFKA_BROKER,
  KAFKA_VIDEO_RESOLUTION_TOPIC,
  KAFKA_VIDEO_SEARCH_INDEX_TOPIC,
};
